version: '3.8'

services:
  localstack:
    container_name: localstack
    image: localstack/localstack
    ports:
      - 4566:4566
    environment:
      - SERVICES=lambda,ssm,sns,s3,dynamodb
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_EXECUTOR=local
      # AWS settings
      - AWS_DEFAULT_REGION=eu-west-1
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./localstack/create-resources.sh:/docker-entrypoint-initaws.d/create-resources.sh
      - ./localstack/:/localstack/
